Fixed anon type in anon union error in m68k.h
Apple Clang 11.0.0 error:
```
capstone/include/capstone/m68k.h:160:3: error: anonymous types declared in an anonymous union are an extension [-Werror,-Wnested-anon-types]
                struct {                    ///< register pair in one operand
                ^
```

(cherry picked from commit 9bc8f9a22e6df69eb1d71f49d69f64c545438556)